# src/main/resources/application.properties

# MongoDB Connection (Replace with your actual credentials and cluster URL)
spring.data.mongodb.uri=mongodb+srv://manjikavi8_db_user:Kavishan1234@cluster0.vxsfzun.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=smartcampus_db

# Run the backend server on port 8000
server.port=8000


# File upload settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB
image.upload.dir=./uploads